### ISSUE TITLE
ads1015 chipset

### ISSUE THREAD

**Issue by FGMGIT** [mmmries/ads1115#1]
Hello @mmmries, I'm trying to work with ads1015 chipset 12bits board with I2C address: 0x48 , on Elixir nerves. Any help on how to adapt your code will be great.

**Comment by mmmries** [comment]
Hi @FGMGIT I don't know all of the differences between the 1115 and 1015 chips. Because it is a 12-bit resolution I think you'll need to look at https://github.com/mmmries/ads1115/blob/e7447ce80e99682f69544c61b676c10d7a063db8/lib/ads1115.ex#L53 which is expecting to read in a 16 bit signed integer from the I2C. I would also check the https://github.com/mmmries/ads1115/blob/master/lib/ads1115/config.ex file to see if the 1015 chip supports the same types of comparisons.

I've never used the 1015 chip so I'm really not sure what all will be different, but I would probably try to use this library as-is at least once and do a basic read of the `{:ain0, :gnd}` to see if the I2C protocol is the same. Or it might be better to just fork this library (it's only 2 files of actual code) and start with that.

**Comment by FGMGIT** [comment]
Hi @mmmries thank you for your help, the specifications seems to be exactly the same the only thing it changes is SPS data rate. In the waveshare sense-hat board I'm working, the I2C address it is the same for that chipset 0x48 or 72 in your code. I will try to change 16bit resolution to 12bit and rewrite the code for the 1015 chip data rate. I will let you know if works to fork it. 

<img width="816" alt="Captura de pantalla 2020-07-13 a las 20 29 42" src="https://user-images.githubusercontent.com/15965708/87341347-cb297e00-c549-11ea-8c36-6e436da2e989.png">
<img width="818" alt="Captura de pantalla 2020-07-13 a las 20 29 53" src="https://user-images.githubusercontent.com/15965708/87341351-cc5aab00-c549-11ea-9a84-546ff6666073.png">

**Comment by tomjoro** [comment]
Hello! 
I've made changes to support ads1015 after reviewing everything. It's pretty minor because it's the same register set - just seems the data rate is different (but the default works) so you can use it out of the box as long as you convert the return value correctly. 

Regarding the default (those are the same for default), so it works out of box:
* #define RATE_ADS1015_1600SPS (0x0080) ///< 1600 samples per second (default)
* #define RATE_ADS1115_128SPS (0x0080) ///< 128 samples per second (default)

This is all you need to get started. Can someone check my logic here:??
(This is only for 12bit ads1015. I'm not supporting both)
```
@spec custom_read(reference(), I2C.address(), Config.t()) :: {:ok, integer()} | {:error, term()}
  def custom_read(bus, addr, %Config{}=config) do
    with :ok <- set_config(bus, addr, config),
         :ok <- wait_for_reading(bus, addr),
         {:ok, <<val::signed-size(16)>>} <- I2C.write_read(bus, addr, @sensor_register, 2) do

           val = val / 16 # equivalent to val >> 4
           if val > 2047 do   # 0x7FF
             {:ok, val - 4096}  # double 2048
           else
             {:ok, val}
           end
    end
  end
```

The code is pretty clear here: 
https://github.com/adafruit/Adafruit_ADS1X15

I can make a pull request to support both ads1015 and ads1115 if there is interest?
* adding configuration for chip (ads1015 or ads1115)
* adding ads1015 data rates
* adding conversion appropriate for 12bit or 16bit.

**Comment by mmmries** [comment]
@tomjoro thanks for taking a look at that and narrowing down what needs to be different. Do you have an ADS1015 chip that you can test your changes with? I would love to add support for the device, I just don't want to make a change that we can't verify. I would hate for someone else to pull in this library and have a frustrating experience debugging something that should have been simple.

If you can propose some changes and test your changes then I'd love to pull them into the project

**Comment by tomjoro** [comment]
I have a ADS1015 and I have tested with it and it is working. I haven't had time to do a full update to the code base so I don't have a pull request. I'll try to get some time to make a pull request.

**Comment by mmmries** [comment]
❤️ 💛 💙 💚 💜 that sounds amazing and thanks for testing. If I can help with part of the PR feel free to drop me a note. If it's easiest you can just put up your changes as-is and I can try to find an easy integration point for those changes.

Just wanted to offer help

**Comment by tomjoro** [comment]
I noticed some of the other nerves "drivers" use a gen_server for state management. I was think it might be overkill here so we'd need to add some sort of parameter to specify the target chipset. I'll start the PR to get things rolling :) . Thanks.
